markdown:         kramdown
highlighter:      rouge
theme: jekyll-theme-architect
kramdown:
  auto_ids: true 
# Permalinks
permalink:        pretty
# Social
title: Powernic
description: The most popular HTML, CSS, and JS framework in the world. 
