markdown:         kramdown
highlighter:      rouge
theme: jekyll-theme-architect
kramdown:
  auto_ids: true 
# Permalinks
permalink:        pretty
# Social
title: Bootstrap
description: The most popular HTML, CSS, and JS framework in the world.
twitter: getbootstrap
authors: Mark Otto, Jacob Thornton, and Bootstrap contributors
social_logo_path: /assets/brand/bootstrap-social-logo.png
social_image_path: /assets/brand/bootstrap-social.png
